export const FETCH_WORKSHOPS_ALL_DATA = 'FETCH_WORKSHOPS_ALL_DATA';
export const FETCH_WORKSHOPS_ADULTS_DATA = 'FETCH_WORKSHOPS_ADULTS_DATA';
export const FETCH_WORKSHOPS_KIDS_DATA = 'FETCH_WORKSHOPS_KIDS_DATA';
