export const FETCH_GALLERY_IMAGES_ADULTS_STUDENTS = 'FETCH_GALLERY_IMAGES_ADULTS_STUDENTS';
export const FETCH_GALLERY_IMAGES_ADULTS_WORKS = 'FETCH_GALLERY_IMAGES_ADULTS_WORKS';
export const FETCH_GALLERY_IMAGES_KIDS_STUDENTS = 'FETCH_GALLERY_IMAGES_KIDS_STUDENTS';
export const FETCH_GALLERY_IMAGES_KIDS_WORKS = 'FETCH_GALLERY_IMAGES_KIDS_WORKS';