export const FETCH_MAIN_SLIDER_IMAGES = 'FETCH_MAIN_SLIDER_IMAGES';
export const FETCH_MAIN_CAROUSEL_IMAGES_STUDENTS = 'FETCH_MAIN_CAROUSEL_IMAGES_STUDENTS';
export const FETCH_MAIN_CAROUSEL_IMAGES_WORKS = 'FETCH_MAIN_CAROUSEL_IMAGES_WORKS';
export const FETCH_MAIN_OPTIONS_IMAGES = 'FETCH_MAIN_OPTIONS_IMAGES';
